# Generated by Django 5.0.1 on 2024-02-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Categrias',
        ),
    ]
