# Generated by Django 5.0.1 on 2024-02-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_cat_delete_categrias'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nome',
            field=models.CharField(default='Nome ', max_length=50),
        ),
    ]
